/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103072-g6f0f7bc7fe-20210725"
#endif /* AVUTIL_FFVERSION_H */
